name: Pregunta1

on: 
  push: 
    branches:
      - main
jobs:
  Pregunta1:
    runs-on: ubuntu-latest
    steps:
    
      - name: Step 1 - Crear directorio examen
        run: mkdir examen
        
      - name: Step 2 - Adicionar archivos al directorio examen
        run: |
          cd examen
          echo 'Mensaje examen 1'    > examen01.html
          echo 'Mensaje examen 2'    > examen02.html
          echo 'Mensaje examen 3'    > examen03.html
          echo 'Mensaje examen 4'    > examen04.html
          echo 'Mensaje examen 5'    > examen05.html          
          cd ..
          
      - uses: papeloto/action-zip@v1
        with:
          files: examen/
          dest: examen.zip
                                    
      - name: Step 4 - Verificacion de la creacion de artefactos ZIP
        run: ls -la
